### ISSUE TITLE
非预期的输出值

### ISSUE THREAD

**Issue by xboxwhy5** [Orange-Icepop/LSL#2]
在框中填入非预期的数值时，会导致输出未处理的异常

**Comment by Orange-Icepop** [comment]
> 在框中填入非预期的数值时，会导致输出未处理的异常

何处的框？是添加服务器那里的吗？

**Comment by Orange-Icepop** [comment]
fixed at [commit 5968ca7f078bd04623224514a9241b31c85793da](https://github.com/Orange-Icepop/LSL/commit/5968ca7f078bd04623224514a9241b31c85793da)
